### ISSUE TITLE
Inconsistencies in dots being highlighted on map 

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#61] opened 2018-01-19 16:53 UTC
Volunteer comments:
Couldn't always see the location button on the map e.g 62-68 Clerkenwell Road and 23-25 Paul Street.

**Comment by jessicasalmon** [comment] 2018-01-31 13:28
duplicate of #60. 
Closing this issue and will address it there.

**Closed** 2018-01-31 13:29 UTC
Labels: bug, duplicate
